# Generated by Django 3.0.6 on 2020-06-02 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('RecargasCubacel', '0003_auto_20200601_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranferenciacubacel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
