# Generated by Django 3.0.6 on 2020-06-06 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecargasCubacel', '0005_auto_20200603_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranferenciaCubacel',
        ),
    ]
