# Generated by Django 3.0.6 on 2020-06-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecargasCubacel', '0005_auto_20200603_1541'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
