# Generated by Django 3.0.6 on 2020-06-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_auto_20200610_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciaactual',
            name='SendValue',
            field=models.CharField(max_length=50),
        ),
    ]
