# Generated by Django 3.0.7 on 2020-06-30 19:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuarios', '0008_auto_20200624_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TranferenciaCubacel',
            new_name='TranferenciaGeneral',
        ),
    ]
