# Generated by Django 3.0.7 on 2020-07-05 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuarios', '0009_auto_20200630_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranferenciageneral',
            name='accountNumber',
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.IntegerField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tranferenciageneral',
            name='contacto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='Usuarios.Contacto'),
            preserve_default=False,
        ),
    ]
