# Generated by Django 3.0.7 on 2020-07-06 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MercadoPago', '0002_auto_20200705_2352'),
        ('Usuarios', '0011_auto_20200705_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranferenciageneral',
            name='clienteMercadoPago',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='MercadoPago.ClienteMercadoPago'),
        ),
    ]
