# Generated by Django 3.0.7 on 2020-07-15 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuarios', '0012_auto_20200705_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranferenciageneral',
            name='clienteMercadoPago',
        ),
        migrations.AlterField(
            model_name='transferenciaactual',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
