# Generated by Django 3.0.7 on 2020-08-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0016_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='modified',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='votosN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='votosP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
