# Generated by Django 3.0.7 on 2020-09-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0022_auto_20200902_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranferenciageneral',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Usuarios.Contacto'),
        ),
    ]
