# Generated by Django 3.0.7 on 2020-09-07 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usuarios', '0023_auto_20200906_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='user',
        ),
        migrations.AddField(
            model_name='contacto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
