# Generated by Django 3.0.7 on 2020-09-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0024_auto_20200906_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciaactual',
            name='cant',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
