# Generated by Django 3.0.7 on 2020-09-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0026_tranferenciageneral_transferref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservasHechas',
            fields=[
                ('fechaStart', models.DateField()),
                ('fechaEnd', models.DateField()),
                ('cant', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=range, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
