# Generated by Django 3.0.7 on 2020-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0027_auto_20200909_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
