# Generated by Django 3.0.7 on 2020-09-17 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0028_contacto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciaactual',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Usuarios.Contacto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
